---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-vv'

dependencies:
  galaxy:
    collections:
      - name: community.vmware

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest

options:
 package_manager_path: /usr/bin/microdnf
